version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
